Chore/update 2021 07
mozilla-services/syncstorage-rs pull request #1124
Opened 2021-07-30 21:57 UTC by jrconlin

## Description

Update dependencies, rust versions

## Testing

No change to function

## Issue(s)

NA

2021-07-31 02:37 UTC, pjenvey requested changes

2021-07-31 02:37 UTC, pjenvey commented on src/web/extractors.rs
> +        .to_string();
`Cow` can potentially save an alloc here:

```suggestion
        .into_owned();
```

2021-08-02 17:02 UTC, jrconlin commented
(Not why, but rust-analyzer really didn't like `into_owned()` until I rebuilt everything with a `cargo clean`. It absolutely wanted me to use either `String::from()` or `to_string()` here.)

2021-08-02 17:11 UTC, ethowitz approved these changes
Tokenserver changes look good to me ✅

2021-08-02 17:39 UTC, pjenvey approved these changes

2021-08-02 17:42 UTC, merged