chore: update to Rust 1.58 and switch to GCP Rust crate
mozilla-services/syncstorage-rs pull request #1201
Opened 2022-01-19 16:40 UTC by ethowitz

## Description
Update to Rust 1.58 and start using the google-cloud-rust-raw crate instead of vendoring the GCP code.

## Testing

N/A

## Issue(s)

N/A

2022-01-19 18:50 UTC, jrconlin commented
oof. Looks like a minor `fmt` fail. 
Also, did you want to bump things up to `edition="2021"` while you have the chance? From what I've seen, there's no impact to existing code from `fmt` or `clippy`

2022-01-19 19:12 UTC, jrconlin commented
Sigh, and looks like after a `cargo update`, there's a new version of `protobuf`.

2022-01-19 19:14 UTC, ethowitz commented
I suppose we'll need to rebuild the GCP Rust bindings then?

2022-01-19 19:15 UTC, jrconlin commented
Not necessarily, or at least, not a full rebuild should be required. There are steps in the vendored directory you can do. 
 I can also try doing a PR that is just that part.

2022-01-19 19:16 UTC, ethowitz commented
I'll give it a shot!

2022-01-21 20:07 UTC, pjenvey requested changes

2022-01-21 22:57 UTC, jrconlin commented on Dockerfile
> +FROM rust:1.58-buster as builder
I think that if you specify 1.58, it pulls in the latest version subversion.

2022-01-21 22:59 UTC, jrconlin commented on Dockerfile
> +FROM rust:1.58-buster as builder
Just did a `docker pull rust:1.58-buster` and an internal shell 
```rustup show``` shows 1.58.1

2022-01-24 21:08 UTC, pjenvey approved these changes

2022-01-24 21:56 UTC, merged