feat: don't run Tokenserver migrations on startup
mozilla-services/syncstorage-rs pull request #1286
Opened 2022-04-21 22:44 UTC by ethowitz

## Description

Since we're connecting to the pre-existing Tokenserver database, we should not be running the migrations on server startup.

2022-04-21 22:45 UTC, ethowitz commented on Makefile
> +	PATH="./venv/bin:$(PATH)" RUST_LOG=debug RUST_BACKTRACE=full cargo run -- --config config/local.toml
This fixes an unrelated bug that causes `make run` to fail if an item in your path has any whitespace characters in it.

2022-04-22 17:31 UTC, pjenvey requested changes
This needs the e2e tests in CI to run them

2022-04-22 18:20 UTC, ethowitz commented
Removed the `tokenserver_migrate` make task since the migrations will run automatically for any non-release build

2022-04-22 20:44 UTC, ethowitz commented
The e2e tests run against a release build...I will add a line to run the migrations manually in the docker-compose

2022-04-22 21:58 UTC, pjenvey approved these changes

2022-04-25 16:59 UTC, jrconlin approved these changes

2022-04-25 17:47 UTC, merged