WIP Refactor/remove unnecessary syncserverrequest impl
mozilla-services/syncstorage-rs pull request #1295
Opened 2022-04-28 23:27 UTC by taddes

## Description

This task entailed removing unnecessary impl blocks for syncserverrequest, as they were not used. The implementation of the TryFrom trait for HawkIdentifier followed by moving it into `extractors.rs` sufficiently tidied up the code in `mod.rs` scoping the functionality to where the structure is defined and various traits implemented for `HawkIdentifier`

In the Makefile, added a quoting to avoid certain paths with space characters breaking the build. @ethowitz was able to clear this issue up and had dealt with it in the past.

## Testing

Ensuring compilation should be sufficient. Ran into some formatting deltas between CircleCI and clippy in initial tests.

## Issue(s)

Closes [link](link).
https://mozilla-hub.atlassian.net/browse/CONSVC-1693

2022-04-29 15:24 UTC, jrconlin commented on src/web/extractors.rs
> +        // NOTE: `connection_info()` gets a mutable reference lock on `extensions()`, so
Looking at what goes on here, the sequence is all blocking code. Is the concern that we don't want the risk of something modifying the `extensions`?

2022-04-29 16:58 UTC, ethowitz requested changes
Looks great, @taddes! Just a couple of suggestions 👨🏻‍💻

2022-05-09 16:59 UTC, ethowitz commented
I think this needs another rebase after the merging of #1281. Happy to assist if it would be helpful :)

2022-05-17 17:29 UTC, ethowitz approved these changes
Looks great @taddes! :shipit:

2022-05-19 21:37 UTC, merged