Cors2
mozilla-services/syncstorage-rs pull request #1308
Opened 2022-05-13 22:36 UTC by jrconlin

## Description

Set the CORS values explicitly.

## Testing

How should reviewers test?

## Issue(s)

Closes [link](link).

2022-05-13 22:41 UTC, pjenvey requested changes

2022-05-13 22:41 UTC, pjenvey commented on syncstorage/src/settings.rs
> +        s.set_default("cors_allowed_hosts", Some("*"))?;
```suggestion
        s.set_default("cors_allowed_origin", Some("*"))?;
```

2022-05-13 23:27 UTC, pjenvey approved these changes

2022-05-13 23:55 UTC, pjenvey approved these changes

2022-05-17 17:47 UTC, jrconlin commented on syncstorage/src/settings.rs
> +                "UserAgent".to_owned(),
Went with the "Use the official header fields so you don't forget or misspell stuff (you idiot)" approach.

2022-05-17 18:45 UTC, ethowitz submitted a review, later dismissed

2022-05-17 22:09 UTC, pjenvey commented on syncstorage/src/settings.rs
> +                "TEST_IDLES".to_owned(),
What's `TEST_IDLES`?

2022-05-18 23:17 UTC, pjenvey commented on syncstorage/src/settings.rs
> +                "TEST_IDLES".to_owned(),
Whatever it is it's already part of the defaults so disregard my question.

2022-05-18 23:19 UTC, pjenvey requested changes

2022-05-18 23:19 UTC, pjenvey commented on syncstorage/src/settings.rs
> +                cors = cors.send_wildcard();
Testing this locally I see this doesn't solve the issue. Looks like we want this:
```suggestion
                cors = cors.allow_any_origin();
```

2022-06-06 23:47 UTC, pjenvey approved these changes

2022-06-07 19:55 UTC, merged