feat: Return 412 when handling a ':' in offset.
mozilla-services/syncstorage-rs pull request #1347
Opened 2022-06-30 23:50 UTC by jrconlin

## Description

Return a 412 if encountering a ':' in the offset. This possibly resolves an issue with iOS clients.

## Testing

Unit test included.

## Issue(s)

Closes #1345

2022-07-12 22:08 UTC, pjenvey submitted a review, later dismissed
This looks good, just those 2 comment changes could be killed. This does seem to be triggered solely by iOS. There's another issue in the same sentry event triggered by desktop Linux that I'll log a separate issue for.

2022-07-13 13:38 UTC, ethowitz requested changes

2022-07-13 13:38 UTC, ethowitz commented on syncstorage/src/web/extractors.rs
> +            return Err(ValidationErrorKind::FromDetails(
Hmm, is the error returned here being overwritten by the [`map_err` call on line 1288](https://github.com/mozilla-services/syncstorage-rs/blob/54321126d81710d2150f2b7d05b2a1ccb0338e89/syncstorage/src/web/extractors.rs#L1288)? If so, I think that would overwrite the 412 error code with a 400 (I made some changes to the `test_invalid_offset` unit test, and I think I was able to confirm this).

I think we may need to pass through the name and label from the original offset error to the one on line 1288?

2022-10-07 23:28 UTC, pjenvey requested changes
It looks like the issue Ethan pointed out (I just unresolved it) still stands.

I think the special `PRECONDITION_FAILED` `ValidationError` is getting eaten in potentially 2 places. The first one's due to the fact that a serde deserializer constructs the `Offset`, so we're not easily able to propagate the error out of there via its `Deserializer Error` (I have to think about how to get around this again, it's been a while..).

Once that's solved, there's another map_err call in `BsoQueryParams::from_request` that would also eat it.

Let's also add some kind of integration test for this case, here's an easy one for the e2e test suite:

```python
    def test_offset_with_colon(self):
        res = self.app.get(
            self.root + "/storage/xxx_col2?limit=10000&offset=123456:123",
            status=412
        )
```

2024-04-25 15:56 UTC, closed without merging