refactor: implemented wrap_fn for middlewares, clippy warnings on Eq, manual_range_contains
mozilla-services/syncstorage-rs pull request #1374
Opened 2022-08-15 21:37 UTC by taddes

## Description

Implemented middleware with `wrap_fn()` to remove significant boilerplate. Moved bodies of `Service::call()` methods into the function body of `wrap_fn` and registered it in `mod.rs`, which passes in the service and request. Each middleware contains its own logic scoped to the individual module.

Also made some minor refactors due to clippy warnings for `Eq` and the [manual_range_contains warning ](https://rust-lang.github.io/rust-clippy/master/index.html#manual_range_contains)which I had not yet seen. Hopefully it is relatively clear given the range check.

## Testing

Compilation, clarity. 

## Issue(s)

Closes #714

2022-08-25 20:42 UTC, ethowitz requested changes
Looks good so far! Just a few small suggestions. This branch will need a rebase, since I made some changes to the Sentry middleware last week; I'll take a closer look at the Sentry middleware changes after the rebase is pushed up

2023-01-04 17:21 UTC, ethowitz commented
In the next syncstorage and tokenserver release, we'll want to verify on stage that these middlewares are working as expected before we promote to production

2023-01-05 17:19 UTC, jrconlin approved these changes
much nicer without the boilerplate stuff.

2023-01-05 19:24 UTC, ethowitz approved these changes

2023-01-05 19:24 UTC, merged