chore: Switch to libmariadb-dev
mozilla-services/syncstorage-rs pull request #1635
Opened 2024-11-27 11:41 UTC by ghagl

## Description

The MySQL repository causes issues when trying to build for other architectures (non-existent MySQL binaries), therefore the MariaDB packages should instead be used. This has been successfully tested on arm64.

## Testing

Build on all relevant architectures (x86, arm64, ...).

2024-12-04 18:22 UTC, jrconlin approved these changes
Thanks for this. I'm fine switching to mariadb for a lot of reasons, it just hasn't come up as a priority for the team.

2024-12-11 00:42 UTC, pjenvey requested changes

2024-12-11 00:42 UTC, pjenvey commented on Dockerfile
> +    apt-get -q install -y --no-install-recommends libmariadb-dev-compat libmariadb-dev cmake
nit: `libmariadb-dev` is superfluous w/ `libmariadb-dev-compat` (which depends on it)

2024-12-11 00:42 UTC, pjenvey commented on Dockerfile
> +    # We need to install libmariadb-dev to build syncstorage-rs
you can kill this comment entirely

2024-12-11 00:42 UTC, pjenvey commented on Dockerfile
> +    # first, an apt-get update is required for the packages
please kill this comment entirely as well (it was explaining the previous need for calling `apt-get update` twice here)

2024-12-11 00:43 UTC, pjenvey commented
(For reference: where we originally moved away from maria's client: https://github.com/mozilla-services/syncstorage-rs/pull/1435 )

2024-12-27 14:12 UTC, tommie commented
Oh, I just realized I'm doing similar work. I have a branch that upgrades to Diesel 2.x, which uses mysqlclient-sys 0.4.0, which supports finding libmariadb-dev without -compat.

I retained the libmysqlclient code as a build arg option.

- https://github.com/mozilla-services/syncstorage-rs/compare/master...tommie:syncstorage-rs:mariadb?expand=1
- https://github.com/mozilla-services/syncstorage-rs/pull/1644

2025-02-12 14:06 UTC, ghagl commented
Is this PR now redundant by other changes that have already been made upstream?

2025-03-24 18:40 UTC, closed without merging

2025-03-24 18:40 UTC, pjenvey commented
> Is this PR now redundant by other changes that have already been made upstream?

It is as of the recently merged https://github.com/mozilla-services/syncstorage-rs/pull/1665 -- thank you for the PR @ghagl