Draft: Allow using Debian's libmariadb for building, upgrade to Diesel 2.2.6 and refactor Dockerfile
mozilla-services/syncstorage-rs pull request #1644
Opened 2024-12-27 14:12 UTC by tommie

## Description

The end-goal of this PR is to be able to build for ARM64. The MySQL repo only contains client packages for AMD64.
However, this required an upgrade of Diesel to the latest, in order to have mysqlclient-sys find libmariadb.
That, in turn, required adding `RwLock` to Diesel connections.
Unfortunately, it also affects `MigrationError`, which has now become a `dyn StdError`.

There was a note in Cargo.toml about diesel_logging not working, but this seems to have been fixed in 0.4.0: https://github.com/shssoichiro/diesel-logger/blob/a3a7df54823a3a0c922bf8d9b636045f079cecfe/CHANGELOG.md

The changes to the Dockerfile are mostly a separate issue, but since there were no build definitions in docker-compose, I wanted to fix that too, since testing it locally was difficult otherwise.
This refactoring showed that there were incompatible requirements for python-cryptography (because all requirements.txt are now checked at the same time.)

Modifying tests to use health checks instead of delaying 20-30 s speeds up local testing.

## Testing

Existing integration tests.

There's a new build arg MYSQLCLIENTPKG that can select between libmariadb-dev and libmysqlclient-dev.

## Issue(s)

A super-set of #1635

2024-12-27 21:54 UTC, tommie commented
This turned into something grotesque. I'm going to have to split the Diesel upgrade and libmariadb from the Dockerfile refactoring.

2024-12-28 19:12 UTC, tommie commented
> webtest.app.AppError: Bad response: 503 Service Unavailable (not 200 OK or 3xx redirect for http://localhost:8000/1.5/99426/storage/xxx_col1?batch=true)

11 tests fail, all batch tests, but only with the original libmysqlclient. I can occasionally reproduce it on my machine, but not if I build with `--profile dev` and enable `RUST_LOG=debug`... It seems to be a race somewhere. Why it would be affected by the client library, I dunno. Perhaps Diesel does something differently for transactions with MariaDB. Or perhaps it also happens with libmariadb, but more rarely.

---

Locally, I've seen another issue more frequently:

```
mysql-e2e-tests-1  | FAIL: test_users_with_the_same_batch_id_get_separate_data (test_storage.TestStorage)
mysql-e2e-tests-1  | ----------------------------------------------------------------------
mysql-e2e-tests-1  | Traceback (most recent call last):
mysql-e2e-tests-1  |   File "/app/tools/integration_tests/test_storage.py", line 2114, in test_users_with_the_same_batch_id_get_separate_data
mysql-e2e-tests-1  |     self.assertEquals(resp.json, ["b"])
mysql-e2e-tests-1  | AssertionError: Lists differ: ['b', 'i'] != ['b']
mysql-e2e-tests-1  | 
mysql-e2e-tests-1  | First list contains 1 additional elements.
mysql-e2e-tests-1  | First extra element 1:
mysql-e2e-tests-1  | 'i'
mysql-e2e-tests-1  | 
mysql-e2e-tests-1  | - ['b', 'i']
mysql-e2e-tests-1  | + ['b']
```

I'm guessing that's also a race, as I can't seem to trigger it with debug logging enabled.

Looking at recent CircleCI history, I can't find evidence that this is an existing issue. I'll keep trying to reproduce.

2025-01-06 23:33 UTC, jrconlin reviewed
Thank You for doing the leg work on updating diesel! Things look pretty good. I do have a question about adding the batch delete function for spanner, which seems a bit out of scope for this PR.

2025-01-07 08:27 UTC, tommie commented on syncstorage-mysql/src/batch.rs
> +        .execute(&mut *db.conn.write().unwrap())
That may result in a deadlock, so I felt it safer to panic:

> This function will return an error if the RwLock is poisoned. An RwLock is poisoned whenever a writer panics while holding an exclusive lock. An error will be returned when the lock is acquired.

https://doc.rust-lang.org/std/sync/struct.RwLock.html#method.write

(Note `write` will block indefinitely waiting for a lock.)

2025-01-07 08:39 UTC, tommie commented on syncstorage-spanner/src/batch.rs
> +pub async fn delete_for_user_async(db: &SpannerDb, user_id: UserIdentifier) -> DbResult<()> {
Good question. Almost. :) There are E2E tests that don't commit batches, so you end up with garbage, and if you are unlucky, that garbage gets picked up by another E2E test that happens to have the same `(userid, batchid)`, causing weird errors. Esp. the test that hammes user IDs to find a batch collision.

It's made use of in https://github.com/mozilla-services/syncstorage-rs/pull/1644/commits/bc188dd2ab3afe25cf11e22498caf57d3f782f6a in the E2E tests. (Previously, only the primary test user was cleaned up.)

In CircleCI, this isn't a problem since the database is always fresh.

Another approach would be to just do some SQLing in the E2E tests to ensure they have a clean slate every time they start, but this seemed better. Ensuring that all user data is removed also seems more GDPR-compliant.

A third one is to not remove user accounts in E2E tests, but that sounds like an unpleasant storage leak.

2025-01-07 21:57 UTC, jrconlin commented on syncstorage-spanner/src/batch.rs
> +pub async fn delete_for_user_async(db: &SpannerDb, user_id: UserIdentifier) -> DbResult<()> {
Ah, normally we isolate test data from real data a number of ways:
1) We always use a test database (e.g. the emulator or a throw away data store) for any testing we do. Never run tests against prod. 
2) We either use well-known or well-prefixed test data that can be cleaned up reasonably easily should someone goof up and run test against prod.  (That's why you see things like `"DEADBEEF" + uuid.uuid4().hex[:8]` in some test scripts.) It's not perfect, by any stretch, but it allows us to at least attempt to clean up any damage.

I suppose you could also add this function as a `#[test]` so that it's not in production, but available as a test routine for cleanup, if you can't target an explicit test datastore.

2025-01-07 22:38 UTC, tommie commented on syncstorage-spanner/src/batch.rs
> +pub async fn delete_for_user_async(db: &SpannerDb, user_id: UserIdentifier) -> DbResult<()> {
Agreed. I don't have any specific E2E testing needs. When doing the Disesel work, I was simply doing "docker compose up" to run the tests locally. After doing it a couple of times, it started giving spurious failures. Since the Python tests don't have an SQL connection set up already, clearing/recreating the database that way seemed more difficult than just clearing the batch data.

If you prefer, I can look into just running `DELETE` on batch (or all) tables before starting the syncserver in `run.py`. Another approach is clearing the MySQL container data volume when it starts, but since `run.py` runs more than one test suite, perhaps it's nicer to be able to do it for each syncserver restart.

2025-01-07 22:53 UTC, tommie commented on syncstorage-spanner/src/batch.rs
> +pub async fn delete_for_user_async(db: &SpannerDb, user_id: UserIdentifier) -> DbResult<()> {
Actually, since this part is just about local tests, I'll move it to a separate PR, and we can focus on Diesel here.

2025-01-08 08:29 UTC, tommie commented on syncstorage-mysql/src/batch.rs
> +        .execute(&mut *db.conn.write().unwrap())
Given the risk of deadlocks if this ever happens, do you still want me to change them?

2025-01-08 08:36 UTC, tommie commented
I've reverted the batch delete change.

The only question remaining is about the RwLock error handling.

2025-01-08 09:22 UTC, tommie commented on syncstorage-mysql/src/batch.rs
> +        .execute(&mut *db.conn.write().unwrap())
Since we have the timezone difference, I've switched to Err return.

2025-01-09 17:23 UTC, jrconlin requested changes
Looks good! 

Sorry that I missed the bit about using a `Uatomic32`, but I think we should probably address an old bug. 

I don't know if you saw my earlier comment about signed commits. Unfortunately I can't land this PR as is because there are unsigned commits. 

That said, I am wondering if we might want to break this into two different PRs (with signed commits). One that does the `diesel 2.x` update, and a follow up that does the libmaria update? That might make things a bit cleaner between the two and spotting key differences might be a little easier, since folk won't have to context switch.

2025-01-09 17:59 UTC, tommie commented on syncstorage-mysql/src/batch.rs
> +    let batch_id = db.timestamp().as_i64() + COUNTER.fetch_add(1, Ordering::Relaxed) as i64 % 10;
> For single server machines, it's fine, since the Atomic is scoped, but for multi-node servers, there's a reasonable chance for collision.

AFAICT, batch ID uniqueness only matters within a user-ID. So to me it seems this change is a strict improvement even in the multi-node sense.

We can't use user-ID since that doesn't help against conflicts in `(user_id, batch_id)`. The problem is the E2E tests are now running faster, for some reason. They generate more than one batch within 10 ms, creating sporadic E2E test failures. The Spanner backend uses UUIDv4, so perhaps this should too. (I have a comment earlier in the PR that I marked as outdated, where I was keeping a journal of my struggles.)

Randomization would still leave the E2E tests potentially flaky. Adding both `user_id%10` and the counter would work.

2025-01-09 18:01 UTC, tommie commented
> I don't know if you saw my earlier comment about signed commits. Unfortunately I can't land this PR as is because there are unsigned commits.

No, but I still don't see any previous comment about signed commits. :\

CONTRIBUTING says "Sign your git commit." I'm guessing you mean a Signed-Off, and not an actual digital signature?

(Since some projects do squashing, and hate it when I force-push in the middle of a review, I tend to avoid rewriting history during reviews. :)

> One that does the `diesel 2.x` update, and a follow up that does the libmaria update?

I've already split it twice already because it became too big, so sure. I saw you had a branch that referenced this PR. I can continue if you like the direction.

2025-01-09 18:03 UTC, jrconlin commented on syncstorage-mysql/src/batch.rs
> +    let batch_id = db.timestamp().as_i64() + COUNTER.fetch_add(1, Ordering::Relaxed) as i64 % 10;
Ah! I didn't know that was the bug you were trying to address. (Sorry, just figured that you were trying to optimize code. FWIW, for some changes like this one, we've left comments in the PR to describe why we're introducing the change. It can help clarify things and help prevent folk from flagging or questioning some changes.)

2025-01-09 18:05 UTC, jrconlin commented
Huh, weird. 
Or maybe I spaced and only commented on the syncstorage-rs PR that also has unsigned commits. My apologies.

2025-01-09 18:30 UTC, tommie commented
Made #1647 for Diesel 2 (since my branch for this PR is called mariadb.)

2025-01-09 18:33 UTC, tommie commented
BTW, the libmariadb change is basically just the Dockerfile change. Hence why I didn't think it was worth splitting from the start.

2025-01-09 18:45 UTC, jrconlin commented
Yeah, but it's good to have separation around these things, regardless of the scope. This can be useful to untangle future problems without doing a lot of heavy cherry picking. Basically, it's a good habit to develop (and one I keep having to remind myself of.)

2025-03-27 23:16 UTC, pjenvey commented
Thank you tommie! I'm closing this out as it's now superseded by https://github.com/mozilla-services/syncstorage-rs/pull/1665, and we'll continue with the rest of this patch on your already open https://github.com/mozilla-services/syncstorage-rs/pull/1647

2025-03-27 23:16 UTC, closed without merging